### ISSUE TITLE
该问题已不存在

### ISSUE THREAD

**Issue by happytaste** [nacos-group/nacos-coredns-plugin#11]
班门弄斧，谢谢仁兄的及时批评，让自己深知学习路上任重而道远，故而关闭该问题，打扰大家了，抱歉。

**Comment by weiyiysw** [comment]
瞎提问，git都用不明白就来提问，羞不羞。去学学怎么用ssh git clone，再看看你这提问

**Comment by happytaste** [comment]
你说的对，我学艺不精，让你笑话了，我去处理这个问题，谢谢你的批评哈。




| |
kevin zhang
邮箱：cieast1999@163.com
|

Signature is customized by Netease Mail Master

在2019年10月19日 16:38，ysw 写道：

瞎提问，git都用不明白就来提问，羞不羞。去学学怎么用ssh git clone，再看看你这提问

**Comment by happytaste** [comment]
希望今后开发你能考虑我们这些学艺不精的人使用出现的问题。




| |
kevin zhang
邮箱：cieast1999@163.com
|

Signature is customized by Netease Mail Master

在2019年10月19日 20:44，happytaste 写道：
你说的对，我学艺不精，让你笑话了，我去处理这个问题，谢谢你的批评哈。




| |
kevin zhang
邮箱：cieast1999@163.com
|

Signature is customized by Netease Mail Master

在2019年10月19日 16:38，ysw 写道：

瞎提问，git都用不明白就来提问，羞不羞。去学学怎么用ssh git clone，再看看你这提问

**Comment by HaojunRen** [comment]
@weiyiysw 最好请使用礼貌的语言来回答每一位提问者，谢谢

**Comment by happytaste** [comment]
该问题已不存在
