### ISSUE TITLE
build.sh make coredns出错

### ISSUE THREAD

**Issue by huangqinghe** [nacos-group/nacos-coredns-plugin#3]
# coredns/plugin/nacos
plugin/nacos/nacos.go:55:24: e.Proxy.Lookup undefined (type proxy.Proxy has no field or method Lookup)
plugin/nacos/nacos.go:74:23: e.Proxy.Lookup undefined (type proxy.Proxy has no field or method Lookup)
plugin/nacos/setup.go:91:24: undefined: proxy.NewLookup
make: *** [coredns] 错误 2

nacos.go引用coredns proxy plugin时没有 prxoy.Proxy.Lookup方法，未定义。

coredns使用最新版本v1.3.1，请问这个是版本问题吗？

**Comment by JianweiWang** [comment]
only support coredns v1.2.6
