### ISSUE TITLE
nacos-coredns 服务名解析不到

### ISSUE THREAD

**Issue by huangqinghe** [nacos-group/nacos-coredns-plugin#4]
nacos server上有两个服务（nacos-hello和nacos-consumer），服务正常。
我在linux上部署dns-f 正常，但在dig nacos-hello @127.0.0.1 -p 1053时，发现解析不到。
![image](https://user-images.githubusercontent.com/8857314/53393642-dec95880-39d7-11e9-9943-633a37ee68e3.png)

查看coredns的异常日志，如下：
![image](https://user-images.githubusercontent.com/8857314/53393704-091b1600-39d8-11e9-888c-6efd3faadc30.png)

好像是数据结构问题，这个要怎么处理？

**Comment by huangqinghe** [comment]
![image](https://user-images.githubusercontent.com/8857314/53395672-5f3e8800-39dd-11e9-827a-c56cc75a7798.png)
把这个改成Nacos-DNS:v1.0.1，问题解决！

**Comment by 829** [comment]
相同的问题，按楼上解决，多谢。
